[build-system]
requires = ["flit_core >=3.2,<4", "sphinx-thunlp-theme>=0.0.9", "sphinx-mathjax-offline"]
build-backend = "flit_core.buildapi"

[project]
name = "infodeslib"
authors = [{name = "Anonymous", email = "anonymous@gmail.com"}]
dynamic = ["version", "description"]
